/*************************************
@@Zoo
paste解锁订阅
日期:2022.11.10
[rewrite_local]
^https?:\/\/api\.apphud\.com\/v1\/customers url script-response-body https://raw.githubusercontent.com/Crazy-Z7/Scrip/main/paste.js
^https:\/\/api\.mixpanel\.com\/track\/\?ip=1 url reject-200
hostname = api.apphud.com
**************************************/
var body = $response.body.replace(/.+/g, '"{\n  \"data\" : {\n    \"results\" : {\n      \"locale\" : \"zh_CN\",\n      \"id\" : \"a40c3648-06ac-4ee8-b515-83f692496fcf\",\n      \"created_at\" : \"2022-11-10T15:00:03.419Z\",\n      \"subscriptions\" : [\n        {\n          \"id\" : \"f21b04f1-b48a-427c-aeac-22de1ad4fb93\",\n          \"unit\" : \"year\",\n          \"group_id\" : \"237801a2\",\n          \"autorenew_enabled\" : false,\n          \"expires_at\" : \"2099-11-24T15:00:19.000Z\",\n          \"in_retry_billing\" : false,\n          \"introductory_activated\" : true,\n          \"cancelled_at\" : null,\n          \"platform\" : \"ios\",\n          \"product_id\" : \"com.wiheads.paste.macos.subscription.annual\",\n          \"retries_count\" : 0,\n          \"started_at\" : \"2022-11-10T15:00:20.000Z\",\n          \"local\" : false,\n          \"next_check_at\" : \"2022-11-24T15:07:19.000Z\",\n          \"kind\" : \"autorenewable\",\n          \"units_count\" : 1,\n          \"environment\" : \"production\",\n          \"status\" : \"trial\"\n        }\n      ],\n      \"paywalls\" : [\n        {\n          \"default\" : true,\n          \"variation_identifier\" : null,\n          \"variation_name\" : null,\n          \"id\" : \"e8f6c54e\",\n          \"items\" : [\n            {\n              \"product_id\" : \"com.wiheads.paste.macos.subscription.monthly\",\n              \"id\" : \"661199d9\",\n              \"store\" : \"app_store\",\n              \"name\" : \"Monthly Subscription\"\n            },\n            {\n              \"product_id\" : \"com.wiheads.paste.macos.subscription.annual\",\n              \"id\" : \"516a4f97\",\n              \"store\" : \"app_store\",\n              \"name\" : \"Annual Subscription\"\n            },\n            {\n              \"product_id\" : \"com.wiheads.paste.macos.subscription.annual.family\",\n              \"id\" : \"b2cd7cfe\",\n              \"store\" : \"app_store\",\n              \"name\" : \"Annual Family Subscription\"\n            }\n          ],\n          \"from_paywall\" : null,\n          \"identifier\" : \"default\",\n          \"experiment_id\" : null,\n          \"experiment_name\" : null,\n          \"json\" : null,\n          \"name\" : \"Default Paywall\"\n        }\n      ],\n      \"user_id\" : \"84D66F10-C169-4547-B3C3-E2DD3D2A345F\",\n      \"currency\" : {\n        \"id\" : \"a5604c08-9833-4d8b-a677-f31e7717d8e5\",\n        \"country_code\" : \"CN\",\n        \"code\" : \"CNY\"\n      },\n      \"devices\" : [\n\n      ]\n    },\n    \"meta\" : null\n  },\n  \"errors\" : null\n}\n"'); $done({body});
