/**********************************************
@@Zoo
我的番茄解锁订阅
日期:2022.12.03
[rewrite_local]
^https?:\/\/api\.revenuecat\.com\/v1\/receipts url script-response-body https://raw.githubusercontent.com/Crazy-Z7/Scrip/main/wdfq.js
hostname = api.revenuecat.com
**********************************************/
var body = $response.body.replace(/.+/g, '"{\n  \"request_date_ms\" : 1670074913039,\n  \"request_date\" : \"2022-12-03T13:41:53Z\",\n  \"subscriber\" : {\n    \"non_subscriptions\" : {\n\n    },\n    \"first_seen\" : \"2022-12-03T13:39:35Z\",\n    \"original_application_version\" : \"11427\",\n    \"other_purchases\" : {\n\n    },\n    \"management_url\" : \"https:\/\/apps.apple.com\/account\/subscriptions\",\n    \"subscriptions\" : {\n      \"com.MINE.PomodoroTimer.plus.yearly\" : {\n        \"original_purchase_date\" : \"2022-12-03T13:41:02Z\",\n        \"expires_date\" : \"2999-12-10T13:41:01Z\",\n        \"is_sandbox\" : false,\n        \"refunded_at\" : null,\n        \"unsubscribe_detected_at\" : \"2022-12-03T13:41:49Z\",\n        \"grace_period_expires_date\" : null,\n        \"period_type\" : \"trial\",\n        \"purchase_date\" : \"2022-12-03T13:41:01Z\",\n        \"billing_issues_detected_at\" : null,\n        \"ownership_type\" : \"PURCHASED\",\n        \"store\" : \"app_store\",\n        \"auto_resume_date\" : null\n      }\n    },\n    \"entitlements\" : {\n      \"Yearly\" : {\n        \"grace_period_expires_date\" : null,\n        \"purchase_date\" : \"2022-12-03T13:41:01Z\",\n        \"product_identifier\" : \"com.MINE.PomodoroTimer.plus.yearly\",\n        \"expires_date\" : \"2999-12-10T13:41:01Z\"\n      },\n      \"Plus\" : {\n        \"grace_period_expires_date\" : null,\n        \"purchase_date\" : \"2022-12-03T13:41:01Z\",\n        \"product_identifier\" : \"com.MINE.PomodoroTimer.plus.yearly\",\n        \"expires_date\" : \"2999-12-10T13:41:01Z\"\n      }\n    },\n    \"original_purchase_date\" : \"2022-12-03T13:38:48Z\",\n    \"original_app_user_id\" : \"$RCAnonymousID:cec31aad466a40f1814a93aa427fcec6\",\n    \"last_seen\" : \"2022-12-03T13:39:35Z\"\n  }\n}"'); $done({body});
